"$schema" = 'https://starship.rs/config-schema.json'

palette = 'nord'

format = """
[î‚¶](nord10)\
$os\
$username[@](bg:nord10 fg:nord0)$hostname\
[î‚°](bg:nord9 fg:nord10)\
$directory\
[î‚°](bg:nord8 fg:nord9)\
$git_branch$git_commit\
[î‚°](bg:nord7 fg:nord8)\
$package\
$golang\
$nodejs\
$php\
$python\
$rust\
$terraform\
$aws\
[î‚°](bg:nord4 fg:nord7)\
$cmd_duration\
[î‚°](fg:#d9dee9)\
$time\
[î‚°](fg:nord0)\
$line_break\
$character
"""

[os]
disabled = false
format = "[$symbol ]($style)"
style = "fg:nord0 bg:nord10"

[os.symbols]
Windows = "îœ"
Ubuntu = "ó°•ˆ"
SUSE = "ïŒ”"
Raspbian = "ó°¿"
Mint = "ó°£­"
Macos = "ó°€µ"
Manjaro = "ïŒ’"
Linux = "ó°Œ½"
Gentoo = "ó°£¨"
Fedora = "ó°£›"
Alpine = "ïŒ€"
Amazon = "ï‰°"
Android = "îœŽ"
AOSC = "ïŒ"
Arch = "ó°£‡"
Artix = "ó°£‡"
CentOS = "ïŒ„"
Debian = "ó°£š"
Redhat = "ó±„›"
RedHatEnterprise = "ó±„›"

[palettes.nord]
nord0 = '#2E3440'
nord1 = '#3B4252'
nord2 = '#434C5E'
nord3 = '#4C566A'
nord4 = '#D8DEE9'
nord5 = '#E5E9F0'
nord6 = '#ECEFF4'
nord7 = '#8FBCBB'
nord8 = '#88C0D0'
nord9 = '#81A1C1'
nord10 = '#5E81AC'
nord11 = '#BF616A'
nord12 = '#D08770'
nord13 = '#EBCB8B'
nord14 = '#A3BE8C'
nord15 = '#B48EAD'

[aws]
format = '[ $symbol($profile )(\($region\) )]($style)'
style = "fg:nord0 bg:nord7"
symbol = 'ðŸ…° '

[git_branch]
format = "[ $symbol$branch(:$remote_branch) ]($style)"
symbol = "ó°˜¬ "
style = "fg:nord0 bg:nord8"

[git_status]
disabled = true

[package]
format = "[ ó°— $version ]($style)"
style = "fg:nord0 bg:nord7"
disabled = true

# Languages

[python]
symbol = 'ó°Œ  '
format = "[ $symbol($version )]($style)"
style = "fg:nord0 bg:nord7"

[rust]
symbol = 'îž¨ '
format = "[ $symbol($version )]($style)"
style = "fg:nord0 bg:nord7"

[golang]
symbol = 'go'
format = "[ $symbol($version )]($style)"
style = "fg:nord0 bg:nord7"

[nodejs]
symbol = 'ó°Œž '
format = "[ $symbol($version )]($style)"
style = "fg:nord0 bg:nord7"

[php]
symbol = 'î˜ˆ '
format = "[ $symbol($version )]($style)"
style = "fg:nord0 bg:nord7"

[terraform]
symbol = 'ó°˜¦ '
format = "[ $symbol($version )]($style)"
style = "fg:nord0 bg:nord7"
disabled = false

[cmd_duration]
format = "[ ó°”š $duration ]($style)"
style = "fg:#2e3440 bg:#d9dee9"

[hostname]
ssh_only = false
style = "fg:nord0 bg:nord10"
format = "[$ssh_symbol$hostname ]($style)"
ssh_symbol = "î¬ "

[shell]
disabled = false

[username]
show_always = true
format = '[$user]($style)'
style_user = "fg:nord0 bg:nord10"

[directory]
style = "fg:nord0 bg:nord9"
read_only = "î©µ "
format = "[ ó°‰‹ $path ]($style)[$read_only]($read_only_style)"
read_only_style = "fg:nord0 bold bg:nord9"

[character]
success_symbol = "[ Â»](bold green)"
error_symbol = "[ Â»](bold red)"
vimcmd_symbol = "[ î˜« >](bold green)"

[time]
disabled = false
format = " [$time]($style) "
style = "bold fg:nord2"
time_format = "%R"
