"$schema" = "https://starship.rs/config-schema.json"
palette = "nord"
format = """
[](nord10)\
$os\
$username[@](bg:nord10 fg:nord0)$hostname\
[](bg:nord9 fg:nord10)\
$directory\
[](bg:nord8 fg:nord9)\
$git_branch$git_commit\
[](bg:nord7 fg:nord8)\
$package\
$golang\
$nodejs\
$php\
$python\
$rust\
$terraform\
$aws\
[](bg:nord4 fg:nord7)\
$cmd_duration\
[](fg:#d9dee9)\
$line_break\
$character
"""

[os]
disabled = false
format = "[$symbol ]($style)"
style = "fg:nord0 bg:nord10"

[os.symbols]
AOSC = ""
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Fedora = "󰣛"
Gentoo = "󰣨"
Linux = "󰌽"
Macos = "󰀵"
Manjaro = ""
Mint = "󰣭"
NixOS = ""
Raspbian = "󰐿"
RedHatEnterprise = "󱄛"
Redhat = "󱄛"
SUSE = ""
Ubuntu = "󰕈"
Windows = ""

[palettes.nord]
nord0 = "#2E3440"
nord1 = "#3B4252"
nord2 = "#434C5E"
nord3 = "#4C566A"
nord4 = "#D8DEE9"
nord5 = "#E5E9F0"
nord6 = "#ECEFF4"
nord7 = "#8FBCBB"
nord8 = "#88C0D0"
nord9 = "#81A1C1"
nord10 = "#5E81AC"
nord11 = "#BF616A"
nord12 = "#D08770"
nord13 = "#EBCB8B"
nord14 = "#A3BE8C"
nord15 = "#B48EAD"

[aws]
format = '[ $symbol($profile )(\($region\) )]($style)'
style = "fg:nord0 bg:nord7"
symbol = " "

[git_branch]
format = "[ $symbol$branch(:$remote_branch) ]($style)"
symbol = "󰘬 "
style = "fg:nord0 bg:nord8"

[git_status]
disabled = true

[package]
format = "[ 󰏗 $version ]($style)"
style = "fg:nord0 bg:nord7"
disabled = true

# Languages

[python]
symbol = "󰌠 "
format = "[ $symbol($version )]($style)"
style = "fg:nord0 bg:nord7"

[rust]
symbol = " "
format = "[ $symbol($version )]($style)"
style = "fg:nord0 bg:nord7"

[golang]
symbol = "go"
format = "[ $symbol($version )]($style)"
style = "fg:nord0 bg:nord7"

[nodejs]
symbol = "󰌞 "
format = "[ $symbol($version )]($style)"
style = "fg:nord0 bg:nord7"

[php]
symbol = " "
format = "[ $symbol($version )]($style)"
style = "fg:nord0 bg:nord7"

[terraform]
symbol = "󰘦 "
format = "[ $symbol($version )]($style)"
style = "fg:nord0 bg:nord7"
disabled = false

[cmd_duration]
format = "[ 󰔚 $duration ]($style)"
style = "fg:#2e3440 bg:#d9dee9"

[hostname]
ssh_only = false
style = "fg:nord0 bg:nord10"
format = "[$ssh_symbol$hostname ]($style)"
ssh_symbol = " "

[shell]
disabled = false

[username]
show_always = true
format = "[$user]($style)"
style_user = "fg:nord0 bg:nord10"

[directory]
style = "fg:nord0 bg:nord9"
read_only = " "
format = "[ 󰉋 $path ]($style)[$read_only]($read_only_style)"
read_only_style = "fg:nord0 bold bg:nord9"

[character]
success_symbol = "[ »](bold green)"
error_symbol = "[ »](bold red)"
vimcmd_symbol = "[  >](bold green)"

[time]
disabled = false
format = " [$time]($style) "
style = "bold fg:nord2"
time_format = "%R"
